# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d93fa0013602906cfddd59d8221aa86ba71da27bd0ce8473f0e3ac98d1a772b476692ca34a18b406a2f1c80f8f6bc0715d1bb2c8feb2cc468a70dfb811779192

test:
  secret_key_base: 1dafc848687c2912a14184f469ad5a84fe442228122086b93fc542082c0bdd010a5ac2c65e987abeefd14e15b78e5b0176793dea3920fc09f8c4079e2f59b05d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
